### PR TITLE
Update for Ubuntu 22.04 and remove reverse proxy setup (configured on a different machine)

### PR DESCRIPTION
**Pull request by remz1337**
Hi, I have updated the script to run on Ubuntu 22.04 with NodeJS v16. I also removed the reverse proxy since it is usually done on a different machine (or manually on the same machine), along with some other minor tweaks.

Also automatically setup PostgreSQL :)

### CODE REVIEW

**Comment by dinger1986** [comment]
largely an all in one install script so dont want to lose nginx or letsencrypt. I know of at least 10 people (personally) who have used the script on a standalone server.

**Comment by dinger1986** [comment]
let me know when this is done and I will review again

**Comment by remz1337** [comment]
What do you think if we make the nginx installation optional (enabled by default)?

**Comment by dinger1986** [comment]
Perfect man thanks

**Comment by dinger1986** [comment]
Looks good man, I wonder do we drop 20.04 altogether or have it working on both?

**Comment by remz1337** [comment]
From what I saw, it should work on both (probably even 18.04). My suggestion would be to either check for either one of them, or simply drop the check altogether and simply add a warning at the beginning of the script and in the documentation that it was only tested on 20.04 and 22.04 (might encourage some to test on other versions)

**Comment by dinger1986** [comment]
yeah makes sense, but people are stupid sometimes lol, ill look at modifying the check for both

**Comment by dinger1986** [comment]
Thanks remz

**Pull request merged**
