### PR TITLE
Dinger1986 master

### PR DESCRIPTION
**Pull request by nicolas-graves**

### CODE REVIEW

**Comment by nicolas-graves** [comment]
Synchronising with base script.

**Comment by nicolas-graves** [comment]
Sorry, was intended for propagating your changes to my fork.

**Comment by dinger1986** [comment]
Happy to merge these, ideally giving the option of Postgres or SQLite would be good, I personally would prefer Postgres just never got to it and haven't done much with vaultwarden in over a year

**Comment by nicolas-graves** [comment]
Very small changes are actually required for postgresql. 
See commits  
https://github.com/nicolas-graves/bitwardenrs_install_script/commit/f6da2c7fba63d364e6144e4fe2635b6cd2848b71 
and 
https://github.com/nicolas-graves/bitwardenrs_install_script/commit/baa7cb2672fa70edfaaed843ca5801ac456e0baa

You might need to configure psql though, I used it with a remote database. I haven't touched these in a long time as well.

**Comment by dinger1986** [comment]
I'll take a look and figure that out maybe add an option for Postgres, have written up afew scripts now creating Postgres dbs, so will see about adding that

**Pull request closed without merging**
